# tb/cocotb_sanity/Makefile
SIM ?= verilator
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/dff.sv
COCOTB_TOPLEVEL = dff
COCOTB_TEST_MODULES = test_dff

include $(shell cocotb-config --makefiles)/Makefile.sim