VERILOG_SOURCES := $(PWD)/../../../rtl/core/rv32i_pkg.sv $(PWD)/../../../rtl/core/rf.sv $(PWD)/../../../rtl/core/controller.sv $(PWD)/../../../rtl/core/decoder.sv $(PWD)/../../../rtl/core/ext.sv 
COCOTB_TOPLEVEL := decoder
COCOTB_TEST_MODULES := test_id

include ../common.mk