VERILOG_SOURCES := $(PWD)/../../../rtl/core/rv32i_pkg.sv $(PWD)/../../../rtl/core/alu.sv $(PWD)/../../../rtl/core/execute.sv
COCOTB_TOPLEVEL := execute
COCOTB_TEST_MODULES := test_exe

include ../common.mk